debug: false
#logging.level.com.camunda.*: INFO

#server.port: 8080

# See the docker-compose to use PostgreSQL
spring:
  datasource:
    #shareable h2 database
    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  h2.console.enabled: true

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none


camunda.bpm:
#  job-execution:
#    deployment-aware: true
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  history-level: FULL